### DISCUSSION TITLE
How can I add colours to Leaflet map

### DISCUSSION THREAD

**Discussion by d-kishorekumar** [Leaflet/Leaflet#9000] [Q&A]
how can I add colour to the Leaflet map?

if I want to add colours to the map instead of standard representation is there any way to add colours to the map (light and dark theme)?

Here I can find a solution which uses the world geo.json file, can we implement the same without any geo.json file? [Leaflet - change map colour](https://stackoverflow.com/questions/28339414/leaflet-change-map-color)

![image](https://github.com/Leaflet/Leaflet/assets/6139661/8b7a1f7f-fede-48ab-88c3-430b9daa9597)

**Comment by Malvoz** [comment]
Perhaps you'll find the following example CSS filter helpful:

```css
/* Example CSS filter, inspired by https://github.com/openstreetmap/openstreetmap-website/issues/2332#issuecomment-867821340 */
@media (prefers-color-scheme: dark) {
  .leaflet-tile-pane {
    filter: invert(100%) hue-rotate(180deg) brightness(95%) contrast(90%);
  }
}
```

Turning this:

<img width="500" src="https://github.com/Leaflet/Leaflet/assets/26493779/5b3ad167-d11f-4523-9cf7-51cffe17aa77">


into this (if the user has enabled dark mode in their user agent):

<img width="500" src="https://github.com/Leaflet/Leaflet/assets/26493779/6d5427f0-efd8-4c14-8009-c2ce429c8794">
