### ISSUE TITLE
can't disable fadeanimation temporarily when using fitBounds()

### ISSUE THREAD

**Issue by adamgundy** [Leaflet/Leaflet#3202]
I can disable the zoom and pan animations when calling fitBounds(), but the tile fade animation is a global setting. this causes issues when printing maps - I call fitBounds() to make sure the map is correctly sized and positioned, but I need to disable ALL animations otherwise it ends up with partial maps (only the first frame gets rendered).

in the case of the tile animation, that means there are missing (or no) tiles printed - any that have to be loaded at the 'new' size start the animation with zero opacity.

I can disable it globally, but that regresses the UI, since I lose the nice tile fade in effect in normal use..

**Comment by adamgundy** [comment]
as well as disabling the global fadeAnimation option, to prevent the 'opacity: 0', I also have to force the tiles to be visible like this:

```css
@media print
{
  .leaflet-tile {
     visibility: visible !important;
  }
}
```

otherwise they are not visible until the 'onload' event triggers - which it seems to after the preview is generated (chrome). in actual fact the tiles are loaded by the browser to make sure the preview works, so forcing them visible works...

which leads to a workaround for the global fadeAnimation issue. this:

```css
@media print
{
  .leaflet-tile {
     opacity: 100 !important;
     visibility: visible !important;
  }
}
```

shows the tiles as expected, but allows the fade animation to work in normal use.
