### ISSUE TITLE
Transform-origin on .leaflet-zoom-animated breaks TransformMarker

### ISSUE THREAD

**Issue by Ugoku** [Leaflet/Leaflet#3800]
Since Leaflet doesn't support rotation of markers (yet), I am using @jacobtoye's [transformmarker](https://github.com/jacobtoye/Leaflet.transformmarker). This worked fine in 0.7.3, but broke in 1.0.0 beta 1: markers aren't being rotated around their center point* anymore.

After a bit of digging, I found that 1.0.0 sets a `transform-origin` property of `0 0` on the `leaflet-zoom-animated` class. This causes markers to be rotated around their top-left corner rather than the correct point.

The fix for this is simple. However, since the transform marker is not an official Leaflet product, I am not sure whether this should be "fixed" in Leaflet itself, or in transformmarker, on on a per-project basis. Can a Leaflet-core contributor please advise?

---

\* center point in my case, but in reality this will depend on the marker's `iconAnchor` point.

**Comment by IvanSanchez** [comment]
> I am not sure whether this should be "fixed" in Leaflet itself, or in transformmarker

The best way to do this is to ensure that transformmaker is compatible with Leaflet 1.0 (or to develop a version/fork/whatever of transformmarker that is).

The jump from Leaflet 0.x.x to Leaflet 1.0.0 means that there are API-breaking changes (see [semver](http://semver.org/)), so it's up to the plugin developers to make sure things work.

**Comment by Ugoku** [comment]
Alright, thanks for your comment. I'll have a look to see if I can implement it in transformmarker and make a PR for it.

**Comment by danzel** [comment]
This one might need a bit more consideration for a change.
We set transform-origin quite broadly, which means we hit markers and things.
It might be tidier if we targeted it at just the things that need it (SVG overlay I think?)

@Ugoku We added this locally to get things working with transformmarker:
```css
/* Fix rotated markers */
.leaflet-marker-icon {
	-webkit-transform-origin: center;
	   -moz-transform-origin: center;
	    -ms-transform-origin: center;
	     -o-transform-origin: center;
	        transform-origin: center;
}
```
