### ISSUE TITLE
Research `image-rendering: crisp-edges`

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#4411]
This might be a possible solution to #3575, but needs research:

https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering

Setting the CSS property  `image-rendering: crisp-edges` in all tiles *should*, in theory, fix #3575's pixel gap by making the image border "crisp" and cancelling blur. This needs a simple change in Leaflet's CSS code and **testing** in Safari.

**Comment by hyperknot** [comment]
I think this is meant for the image resampling algorithm, not for the CSS positioning, so it is unrelated to the CSS positioning bug. Also Chrome doesn't support it: http://caniuse.com/#search=crisp%20edges

**Comment by IvanSanchez** [comment]
It's still worth a try, even if just to make it work in Safari, I guess.

**Comment by hyperknot** [comment]
But this issue is not even related to imgs, I made an example only using divs:
http://playground-leaflet.rhcloud.com/foqi/1/edit?html,output

Also, I believe using this resampling filter would probably have a bad effect for satellite, etc. tile layers.

**Comment by IvanSanchez** [comment]
@hyperknot In theory, this CSS attribute applies to `<div>`s also.

I've just made a playground with `image-rendering: pixelated` and that has no effect at all in Chromium whatsoever, so this is looking bleak :sob:

**Comment by mathiasbynens** [comment]
FWIW, all browsers support this CSS property in some form.

```css
foo {
	image-rendering: -webkit-optimize-contrast; /* Old Android, Safari, UC Browser */
	image-rendering: -moz-crisp-edges; /* Firefox */
	image-rendering: crisp-edges; /* Safari */
	image-rendering: pixelated; /* Chrome & Opera */
	/* Note: keep this declaration at the bottom until
	   https://github.com/postcss/autoprefixer/issues/632 is fixed. */
	-ms-interpolation-mode: nearest-neighbor; /* IE */
}
```
