### ISSUE TITLE
SVG workaround styles do not accommodate custom panes

### ISSUE THREAD

**Issue by jwoyame** [Leaflet/Leaflet#4600]
There are two workarounds in leaflet.css that address SVG issues with Joomla! 3.x and Firefox.
These patches fix their respective issues only for the overlay pane. I wanted to document this and discuss whether or not they should accomodate any SVG-based pane, using `.leaflet-container .leaflet-pane > svg` instead. Or, do we leave it alone, as these fixes probably have very little relevance today.

See #3649, #3452
```css
/* .leaflet-container svg: reset svg max-width decleration shipped in Joomla! (joomla.org) 3.x */
/* .leaflet-container img: map is broken in FF if you have max-width: 100% on tiles */
.leaflet-container .leaflet-overlay-pane svg,
.leaflet-container .leaflet-marker-pane img,
.leaflet-container .leaflet-tile-pane img,
.leaflet-container img.leaflet-image-layer {
	max-width: none !important;
	}
```

See #1807
```css
/* workaround for https://bugzilla.mozilla.org/show_bug.cgi?id=888319 */
.leaflet-overlay-pane svg {
	-moz-user-select: none;
	}
```
