### ISSUE TITLE
Undocumented path opacity change → unexpected rendering differences in 1.0

### ISSUE THREAD

**Issue by garthk** [Leaflet/Leaflet#4932]
Expected behaviour:

* [`CHANGELOG.md`](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md) gives sufficient detail that users can identify which code they'll need to change in order to upgrade

Current behaviour:

*  [`CHANGELOG.md`](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md) lacks detail on changes to default styles 

Extra keywords for those trying to find what they suspect might be a bug:

* anti-aliasing
* jagged

Background:

Consider polygon feature boundaries from an `L.GeoJSON` with the `style` function returning:

```js
{
    weight: 1,
    color: '#ff1493',
    fill: false,
}
```

In Chrome 53.0.2785.116 (64-bit), 0.7.7 and 1.0RC3 render this differently:

![Example contrasting 0.7.7 to 1.0RC3](http://i.imgur.com/DEmw18j.png)

Digging into the SVG, the final style for the path in 0.7.7 was:

```css
.final-path-style {
    stroke-linejoin: round;
    stroke-linecap: round;
    stroke: rgb(255, 20, 147);
    stroke-opacity: 0.5;
    stroke-width: 1;
    fill: none;
}
```

… and, in 1.0RC3:

```css
.final-path-style {
    stroke: rgb(255, 20, 147);
    stroke-opacity: 1;
    stroke-width: 1;
    stroke-linecap: round;
    stroke-linejoin: round;
    fill: none;
}
```

Note the `stroke-opacity` change. Now we know what we're looking for, we can spot the changed default for `opacity` in the API docs ([0.7.7](http://leafletjs.com/reference.html#path-opacity), [1.0RC3](http://leafletjs.com/reference-1.0.0.html#path-opacity)). Slowly scrolling both documents looking for changes is a poor upgrade experience, however.

I don't find any relevant results in [`CHANGELOG.md`](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md) for "stroke" or "opacity", though there is this oblique reference:

> Improved default vector layer styles.

I'm afraid my users didn't agree the heavier, jaggier lines were "improved", but ne'er mind. Let's enumerate the changes so people know what to override.
