### ISSUE TITLE
Want Chinese and English are arranged in a horizontal arrangement, the text appears horizontal arrangement, but the results of the text is arranged vertically.

### ISSUE THREAD

**Issue by wuxiashuangji** [Leaflet/Leaflet#5693]
![img 2](https://user-images.githubusercontent.com/21117027/29018434-9ded66b2-7b8d-11e7-9ad8-ce8b950b8283.png)

I can't resoloved this problem ,when i can use api divIcon ,i need some help, thanks!!!
1. Want Chinese and English are arranged in a horizontal arrangement, the text appears horizontal arrangement, but the results of the text is arranged vertically.
2.  I can not  resolve it by css.
3. ''divIcon'' ,this api give me some trouble. sometimes i want to Customize the icon

my css
```css

 .icon-title>div {
			position: absolute;
			/*必须要添加,不然定位不准,自定义divIcon需要给添加个div,取类名*/
			/* display: inline-block; */
			font-size: 14px;
			padding: 5px;
			color: #402406;
			border: 2px solid #72400b;
			border-radius: 12px;
			background: rgba(255, 255, 255, .8);
			transform: translate3d(-50%, -200%, 0);
			writing-mode: vertical-lr;/* writing-mode: vertical-rl;*/    /*this also can't resolve it*/
			text-align: center;
		}
```
my js
```javascript
	/**
	* 自定义divIcon,定义内容放置在html属性中
	 *
	 * */
L.marker(item.position, {	
	icon: L.divIcon({ 
		className: 'icon-title noLine-icon',
		html: '<div>' + '中国电信亚 hello world !太信息引擎 ' + '</div>', 
		iconSize: null, 
		// bgPos: [-100, 200],
		iconAnchor: [0,20 ], 
		popupAnchor: [5, -40] //点击弹出的popup位置相对于原先的偏移量
				
	})
   

})
```

## Development environment

- Leaflet version I'm using: leaflet v1.0.6
- Browser (with version) I'm using:   Chrome 60.0.3112.78

## Others have also encountered similar problems

https://gis.stackexchange.com/questions/227741/divicon-vertical-text
