### ISSUE TITLE
Nearest-neighbour interpolation when zooming into image tiles

### ISSUE THREAD

**Issue by JobLeonard** [Leaflet/Leaflet#5883]
I hope this isn't a complete duplicate - I did a search of the open and closed issues, and issue #4411 comes close to what I have in mind, but it's closed, but browser support for this has also changed since it was closed. Also only specifically looks at `image-rendering: crisp-edges`, which is not exactly the same thing.

Example use-case: we're using leaflet in our [genomic data viewer](https://github.com/linnarsson-lab/loom-viewer) to display a heatmap of gene expression of the full data matrix. Here is an old gif, from before we implemented the UI (and switched to a better color map):

![heatmap-ordered-dither](https://user-images.githubusercontent.com/259840/32101345-184a031a-bb18-11e7-8bc0-cce17c68acfe.gif)

Since each of those pixels represents an individual cell with a specific heat map value, they should remain square when zooming in far enough.

I've been using this tweak to the leaflet CSS with decent enough success for that, although I haven't thoroughly tested _every_ possible browser:

```css
/* Leaflet crispness override */
.leaflet-container .leaflet-overlay-pane svg,
.leaflet-container .leaflet-marker-pane img,
.leaflet-container .leaflet-shadow-pane img,
.leaflet-container .leaflet-tile-pane img,
.leaflet-container img.leaflet-image-layer {
  max-width: none !important;
  /* Preserve crisp pixels with scaled up images */
  image-rendering: optimizeSpeed;             /* Legal fallback */
  image-rendering: -moz-crisp-edges;          /* Firefox        */
  image-rendering: -o-crisp-edges;            /* Opera          */
  image-rendering: -webkit-optimize-contrast; /* Safari         */
  image-rendering: optimize-contrast;         /* CSS3 Proposed  */
  image-rendering: crisp-edges;               /* CSS4 Proposed  */
  image-rendering: pixelated;                 /* CSS4 Proposed  */
  -ms-interpolation-mode: nearest-neighbor;   /* IE8+           */
}
```

See also [the support table in the `image-rendering` entry on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering), and [the page linked from there describing a canvas-based fall-back option](http://phrogz.net/tmp/canvas_image_zoom.html)

**Comment by perliedman** [comment]
Hi @JobLeonard,

cool use of Leaflet! Always fun to see it being put use in completely unexpected use cases.

It's not entirely clear to me what would be a solution for this "issue" - as you've already done, it is possible to set the image rendering for tile layers by overriding the CSS. To me, this looks like a very good solution.

A possible improvement could be to use `TileLayer`'s (or really `GridLayer`'s) [`className option`](http://leafletjs.com/reference-1.2.0.html#tilelayer-classname), assigning your tile layer a custom class, so you could use less general CSS rules.

What would you envision to improve on the current solution?

**Comment by IvanSanchez** [comment]
IMHO the only way of implementing this in a cross-browser way is to have a WebGL rendering of `L.ImageOverlay`s. The shader could have full control of texel interpolation, regardless of CSS support.

**Comment by JobLeonard** [comment]
@perliedman: ah, I hadn't thought of that `className` option! That's much more elegant!

Yes, this solution works perfectly fine for us, since we don't officially support any of the browsers that don't work with this - the app is desktop oriented, not mobile, and expects modern browsers. I just wanted to point out the use-case and how we went at tit.

As for leaflet, I guess the main improvement would be documentation of this possibility so that others won't have to search for it ;). Either in the docs, or in a linked example.

@IvanSanchez: are you sure WebGL has wider support than this CSS option?

Another issue could be the probably extremely rare but still valid use case of having multiple instances. You can have as many 2D canvas elements as you want, but WebGL is a different story (I have a similar problem in that professors regularly want to, get this, _print out webpages_, and because of that I'm semi-stuck with 2D canvas elements instead of [more performant "one WebGL view overlaying everything faking scrolling elements"-hacks](http://idyll-lang.org/idyll-regl-component/). Of course there could be a Canvas-based fallback for that situation.

**Comment by JobLeonard** [comment]
By the way, I just noticed the following rule in `/dist/leaflest.css` [on line 28-31](https://github.com/Leaflet/Leaflet/blob/8bd557886001ed87df4ab4a2ae265ccb622e855e/dist/leaflet.css#[L28-L31])
```css
/* Safari renders non-retina tile on retina better with this, but Chrome is worse */
.leaflet-safari .leaflet-tile {
	image-rendering: -webkit-optimize-contrast;
	}
```

Could that be improved by adding the clauses from above?

The thing is, I don't think nearest neighbour upscaling is desirable in most circumstances: when leaflet is used for display photos, I'm sure many people would prefer linear interpolation.
