### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by vanillajonathan** [Leaflet/Leaflet#7577]
Add a [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS media query for dark mode.

Something like:

```css
.leaflet-bar a,
.leaflet-bar a:hover {
	width: 26px;
	height: 26px;
	line-height: 26px;
	display: block;
	text-align: center;
	text-decoration: none;
}

@media (prefers-color-scheme: light) {
.leaflet-bar a,
.leaflet-bar a:hover {
	background-color: #fff;
	border-bottom: 1px solid #ccc;
	color: black;
        }
}

@media (prefers-color-scheme: dark) {
.leaflet-bar a,
.leaflet-bar a:hover {
	background-color: #000;
	border-bottom: 1px solid #333;
	color: white;
	}
}
```

**Comment by Falke-Design** [comment]
@mourner @johnd0e @IvanSanchez is this a wanted feature?

**Comment by Malvoz** [comment]
A note on backwards compatibility:

The "light" styles (the current styles applied by default) should remain outside a `prefers-color-scheme` media query, otherwise nothing will apply in browsers that do not [support](https://caniuse.com/?search=prefers-color-scheme) that media feature. I.e. only a `prefers-color-scheme: dark` media query is necessary (to override the default light colors).

**Comment by vanillajonathan** [comment]
Something like this:

```css
.leaflet-bar a,
.leaflet-bar a:hover {
	background-color: #fff;
	border-bottom: 1px solid #ccc;
	color: black;
	width: 26px;
	height: 26px;
	line-height: 26px;
	display: block;
	text-align: center;
	text-decoration: none;
}

@media (prefers-color-scheme: dark) {
.leaflet-bar a,
.leaflet-bar a:hover {
	background-color: #000;
	border-bottom: 1px solid #333;
	color: white;
	}
}
```
