### ISSUE TITLE
Use `<button>` for controls

### ISSUE THREAD

**Issue by Malvoz** [Leaflet/Leaflet#7821]
**Is your feature request related to a problem? Please describe.**

`<button>` behaves a bit differently from `<a href="#" role="button">`, this would supersede https://github.com/Leaflet/Leaflet/issues/7368 and https://github.com/Leaflet/Leaflet/issues/7369 (these describe some of the problems with `<a>` controls).

**Describe the solution you'd like**

Use `<button type="button">` over `<a href="#">` for controls (and over `<img tabindex="0">` for markers?).

**Additional context**

  > >Use buttons, not links, for controls
  >
  > Agreed!

  _Originally posted by @mourner in https://github.com/Leaflet/Leaflet/issues/3210#issuecomment-73291846_

  > we should use the button element here

  > This would be a breaking change we can make in Leaflet 2.

  _Originally posted by @jonkoops in https://github.com/Leaflet/Leaflet/issues/7368#issuecomment-976742275_

- Related PR: https://github.com/Leaflet/Leaflet/pull/6248
- Reference: https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/button/button.html

**Comment by Malvoz** [comment]
This change would require a CSS reset for buttons, something along the lines of:

```css
button.leaflet-control {
  background-color: transparent;
  border: none;
  border-radius: 0;
  color: inherit;
  font: inherit;
  line-height: inherit;
  margin: 0;
  padding: 0;
  overflow: hidden;
  text-align: inherit;
  text-transform: none;
  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;
}
```

(this is just a generic class I've been using before, if Leaflet will use a default border-radius for all controls for example there's probably no reason to reset that.)
