### ISSUE TITLE
Popup font drastically smaller since update to 1.8.0

### ISSUE THREAD

**Issue by nenadvicentic** [Leaflet/Leaflet#8385]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Do **NOT** have any CSS rules related to the size of the popup font in your project. Popup will pick up font-size of 12px from the `leaflet.css`:

```css
/* general typography */
.leaflet-container {
	font: 12px/1.5 "Helvetica Neue", Arial, Helvetica, sans-serif;
}
```

2. Upgrade from earlier version (in my case 1.6.x) to 1.8.0.

3. Open a popup on the map.

Font-size is now picked up from the rule:
```css
.leaflet-popup-content {
	margin: 13px 24px 13px 20px;
	line-height: 1.3;
	font-size: 13px;
	font-size: 1.08333em;
	min-height: 1px;
}
```
So, because it's `font-size: 1.08333em;` and because it's `em` and not `rem`, effective font-size is `8.12498px`, which is way too small.

### Expected behavior

Font in the popup is normal size and easy to read.

### Current behavior

Font in the popup is so small (`8.12498px`), that it's practically unreadable.

### Environment

- Leaflet version: 1.8.0
- Browser (with version): Chrome 103, Firefox 103
- OS/Platform (with version): Windows 10, Windows 11

**Comment by Malvoz** [comment]
Duplicate of https://github.com/Leaflet/Leaflet/issues/7952.

This is due to changes that allow fonts to respect users' browser settings (https://github.com/Leaflet/Leaflet/pull/7800, https://github.com/Leaflet/Leaflet/pull/8057).

You may end up with small font sizes if you're also using small fonts on the document. You can change the `font-size` of `.leaflet-container` (or the font size of the document) to correct the font size to your liking.

For example:

```css
.leaflet-container { font-size: 1.2rem; }
```

**Comment by nenadvicentic** [comment]
After reading #7952 , #7800, #8057, I'm see the intention (following user's browser settings), but the reasoning of implementation seems very complicated to me.

On top of that, proposed workaround:

> ```css
> .leaflet-container { font-size: 1.2rem; }
> ```

Does not have any effect on the website. Leaflet's  `.leaflet-container` rule overrides the rule above, placed in `site.css`.

To make a workaround work, I made following override:

```css
.leaflet-popup .leaflet-popup-content {
	font-size: 12px; 
	font-size: 1.2rem;
}
```

Not sure if this approach causes problems further down the way.
